### PR TITLE
Implement patch-based source-map concat strategy

### PR DESCRIPTION
**Pull request by trentmwillis**
**Ready for review.**

Similar to https://github.com/broccolijs/broccoli-concat/pull/102, but this time with support for source-maps.

TODO:
- [x] Support concatenation of sourcemaps (assimilate them)
- [x] ~~Add caching of sourcemap encoder/decoder~~ (will do in follow up)
- [x] Add additional tests
  - [x] Unit tests for new SourceMapConcat class
  - [x] Header/Footer multiline scenarios in existing tests
  - [x] ~~Additional rebuild tests~~ (not needed, covered by unit tests above)
- [x] Cleanup code
- [x] Add any new documentation
- [x] Run benchmarks

### CODE REVIEW

**Comment by trentmwillis** [comment]
Ran some benchmarks:

```bash
FILE_COUNT=1000 DEPTH=3 yarn run bench

# new approach
Average time for build over 10 iterations: 426.2ms
Average time for rebuild over 10 iterations: 101.1ms

# old approach
Average time for build over 10 iterations: 353.1ms
Average time for rebuild over 10 iterations: 332.5ms

FILE_COUNT=10 LARGE_FILES=true yarn run bench

# new approach
Average time for build over 10 iterations: 227.4ms
Average time for rebuild over 10 iterations: 196.4ms

# old approach
Average time for build over 10 iterations: 174.9ms
Average time for rebuild over 10 iterations: 163.3ms
```

So similarly to `SimpleConcat`, initial build is slightly slower, but rebuilds are faster for most cases. However, when dealing with large files, there is pretty much no improvement. This is due to a lot of time being spent in creating the sourcemaps. I'm going to run this against our app to see what a real world example looks like.

**Comment by rwjblue** [comment]
LGTM, let me know once your real world app tests are confirmed working, and we can land + release.

**Comment by trentmwillis** [comment]
Tested this in our app and Travis-Web. Improvements aren't as good as expected, but the pending change-tracking work will make this much better.

That said, I did catch some bugs during my investigation, so I need to write some additional tests and land them prior to these changes.

**Comment by trentmwillis** [comment]
Added some additional rebuild tests. This should be good to land whenever, though we should note that integration with Ember-CLI apps is likely to not see a huge win until change-tracking is supported.

**Comment by stefanpenner** [comment]
@trentmwillis should i merge and release?

**Comment by trentmwillis** [comment]
Unsure. The last I remember we were waiting for a change-tracking approach for Broccoli to be agreed upon. This current implementation isn't a huge improvement, but it would be able to take advantage of change-tracking if it is implemented.

**Comment by trentmwillis** [comment]
This seems to have stalled. I'm going to close, but I'll leave the branch intact in case it is decided to pick this up again in the future.

**Pull request closed without merging**
