### PR TITLE
CI: Replace Node 0.12 with Node 8 and 9

### PR DESCRIPTION
**Pull request by Turbo87**
This should unblock #115 

/cc @stefanpenner @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like this is failing for unrelated reasons... 😞

**Comment by Turbo87** [comment]
@stefanpenner this seems to be related to the `source-map-url` update that also more of less broke `ember-cli-uglify`. Unfortunately we can't pin it here since it is a nested dependency introduced through `fast-sourcemap-concat`.

**Comment by Turbo87** [comment]
I dug further and it seems that `fast-sourcemap-concat@1.2.x` is causing these issues. Using `1.1.x` instead works fine.

**Comment by rwjblue** [comment]
> should this be minor or major version bump?

should be a major version

**Comment by Turbo87** [comment]
@rwjblue done

**Comment by stefanpenner** [comment]
ci still appears unhappy:

```
Warning: ignoring input sourcemap for broken-sourcemap-url.js because ENOENT: no such file or directory, open '/home/travis/build/broccolijs/broccoli-concat/tmp/source_map_concat-input_base_path-4yyLfS7q.tmp/foo/bad-link.map'
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! broccoli-concat@3.2.2 test: `mocha --recursive`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the broccoli-concat@3.2.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-12-05T15_37_56_867Z-debug.log
```

**Comment by Turbo87** [comment]
@stefanpenner see https://github.com/broccolijs/broccoli-concat/pull/117#issuecomment-349256635

**Pull request merged**
