### PR TITLE
changing writeFileSync to  outputFileSync

### PR DESCRIPTION
**Pull request by SparshithNR**
#149

### CODE REVIEW

**Comment by stefanpenner** [comment]
@SparshithNR this has no tests, can you add one plesae

**Comment by SparshithNR** [comment]
Tests are added #151 
@stefanpenner

**Comment by stefanpenner** [comment]
released as v4.2.3 🎉

**Comment by bendemboski** [comment]
@SparshithNR @rwjblue @stefanpenner this is breaking upgrades.

It requires v3.2.1 of `broccoli-output-wrapper`, and gets it as a transitive dependency of `broccoli-plugin`, but the current version (v4.0.1) of `broccoli-plugin` only requires v3.1.1 of `broccoli-output-wrapper`. So anybody with a lock file that upgrades `broccoli-concat` to v4.2.3 without taking other steps to upgrade transitive dependencies will end up with this plugin calling `outputFileSync()` on a pre-`outputFileSync` version of `broccoli-output-wrapper`, resulting in

```
(node:1208) UnhandledPromiseRejectionWarning: Error: Operation outputFileSync is not allowed to use. Allowed operations are readFileSync,existsSync,lstatSync,readdirSync,statSync,writeFileSync,appendFileSync,rmdirSync,mkdirSync,unlinkSync,symlinkOrCopySync,symlinkSync,utimesSync
```

I think we probably want a new release of `broccoli-plugin` with a `broccoli-output-wrapper@v3.2.1` requirement, so this plugin (and any others wanting to use `outputFileSync()`) can require that version of `broccoli-plugin`?

**Comment by bendemboski** [comment]
https://github.com/broccolijs/broccoli-plugin/pull/50

**Comment by SparshithNR** [comment]
@bendemboski  Thanks for detailing the issue and fixing it as well. :)

**Pull request merged**
