### PR TITLE
Demonstrate issue with concatenating sprintf lib

### PR DESCRIPTION
**Pull request by johnnyshields**
This adds two test cases:
- Case 1: concat sprintf lib by itself, which produces a [valid sourcemap](https://sourcemaps.io/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fjohnnyshields%2Fbroccoli-concat%2Ftest-sprintf%2Ftest%2Fexpected%2Fsprintf-alone.js) (no issue)
- Case 2: concat sprintf lib with another js file afterwards, which produces an [**invalid** sourcemap](https://sourcemaps.io/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fjohnnyshields%2Fbroccoli-concat%2Ftest-sprintf%2Ftest%2Fexpected%2Fsprintf-multi.js). Although the error says the failure is occurring on `first.js`, the root cause is actually `sprintf.js`--i.e. whichever file comes after `sprintf.js` will fail.

I've integrated a sourcemap validator into the tests to check for validity.

Other notes:
- You can get a second opinion on sourcemap validity using [sourcemaps.io](http://sourcemaps.io) which uses a [Python lib as its engine.](https://github.com/mattrobenolt/sourcemap-validator) Both the JS lib I'm using and [sourcemaps.io](http://sourcemaps.io) agree that Case 1 is valid and Case 2 is invalid.
- Here is a demo ember repo which also replicates the same issue: https://github.com/johnnyshields/ember-sourcemap-issue. Because broccoli-concat makes an invalid sourcemap (i.e. vendor.js / vendor.map are invalid), the build will later fail when broccoli-uglify-sourcemap attempts to minify it.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@stefanpenner pinging regarding this issue.

**Comment by cdeeter** [comment]
Also seeing this issue! Would love to know if this would be resolved soon. It's blocking our deploys. :/

**Comment by johnnyshields** [comment]
@stefanpenner @ef4 pinging on this issue

**Comment by jhilden** [comment]
@johnnyshields thanks for reproducing this issue.  Do you also have a lead on what the solution would be?  We are also facing this issue and it would be great to have sourcemaps in production.

**Comment by johnnyshields** [comment]
@jhilden no I do not, I'm not at all familiar with the codebase and unfortunately don't have the bandwidth to study it. @stefanpenner @ef4 please help.

**Comment by stefanpenner** [comment]
@johnnyshields thanks, fully intend to. Been totally swamped :S my apologies.

**Comment by jhilden** [comment]
@stefanpenner I'm also at emberconf and I would be very willing to help out with this issue, but I don't really know where to start, yet.

**Comment by stefanpenner** [comment]
@jhilden maybe after my talk Wednesday, we can sit down and dig in.

**Comment by NullVoxPopuli** [comment]
I just ran in to this issue when trying to deploy my staging environment.
I ran 
```
grep -lr --include=*.js sourceMappingURL bower_components/ | xargs sed -i 's/sourceMappingURL//g'
```

to get it working, but obviously not ideal.
Looking forward to progress on this!

**Comment by johnnyshields** [comment]
@stefanpenner pinging on this issue.

**Comment by johnnyshields** [comment]
@stefanpenner any progress on this issue?

**Comment by stefanpenner** [comment]
> @stefanpenner any progress on this issue?

Started doing some ground-work on this yesterday. e.g cleaning up related PR and this project and fast-sourcemap-concat. Also did a-bit of testing to see  how easy it is to detect such malformed maps, we should be able to detect a broken map during `fast-sourcemap-concat`'s map assimilation, and if we detect one my current thought is we should:

1. warn (with maybe an option to throw)
2. disgard the map, instead create a new map which is merely the boundaries of the current file.

**Comment by stefanpenner** [comment]
Thanks, I finally got a chance to get this project up to date with the lastest fast-sourcemap-concat which has improved support for malformed source-maps. Landed tests inspired by this production here https://github.com/broccolijs/broccoli-concat/pull/126 and as v3.4.0.

It's sad how easy it is to let things slip, sorry about that. But your test cases will help ensure we don't regress in the future.

**Comment by johnnyshields** [comment]
@stefanpenner thank you.

**Comment by stefanpenner** [comment]
@johnnyshields thanks for your patience and the good reproduction!

**Pull request closed without merging**
